language: generic

services:
  - docker

deploy:
  - provider: elasticbeanstalk
    region: us-west-2
    app: "my-first-app"
    env: "Myfirstapp-env"

    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket_name: "my-first-app-bucket-us-west-2"

    bucket_path: "docker"

    on:
      branch: main

  - provider: elasticbeanstalk
    region: ap-northeast-2
    app: "test-app"
    env: "Testapp-env"

    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket_name: "my-first-app-bucket-2021"

    bucket_path: "docker"

    on:
      branch: testing      